Initial tests for Scroller
cadcc/Pantalla-CaDCC pull request #1
Opened 2016-11-14 08:01 UTC by crandrade

- [x] Birthdays

2016-11-15 01:56 UTC, m4droid submitted a review, later dismissed
Comentarios agregados. Probar con la resolución de la pantalla de la oficina (1366x768 ?)

2016-11-15 01:56 UTC, m4droid commented on app/index.html
> +        <div class="">
Clases vacías?

2016-11-15 01:56 UTC, m4droid commented on app/index.html
> +            <scroller ng-hide="$root.isScreenRefreshing">Chupenelpicos</scroller>
Dat message

2016-11-15 01:56 UTC, m4droid commented on app/index.html
> +        <div class="">
Otra clase vacía

2016-11-15 01:56 UTC, m4droid commented on app/index.html
> +    <script src="scripts/directives/scroller.js"></script>
El nombre de la directiva no es correcto.

2016-11-15 01:56 UTC, m4droid commented on app/index.html
> +    <script src="scripts/controllers/about.js"></script>
Esta directiva no debería existir.

2016-11-15 01:56 UTC, m4droid commented on app/scripts/controllers/about.js
> +'use strict';
Esta directiva no debería existir.

2016-11-15 01:56 UTC, m4droid commented on app/scripts/directives/scroller.js
> +  .directive('scroller', function () {
Nombre de la directiva incorrecto. Mejor birthdays?

2016-11-15 01:56 UTC, m4droid commented on app/scripts/directives/scroller.js
> +                  var months = ['enero',
Mejorar indentación (a la Python pls)

2016-11-15 04:18 UTC, crandrade commented on app/index.html
> +    <script src="scripts/directives/scroller.js"></script>
Es correcto

2016-11-15 04:18 UTC, crandrade commented on app/scripts/directives/scroller.js
> +  .directive('scroller', function () {
Es correcto

2016-11-21 02:57 UTC, m4droid requested changes
Cambios no son consistentes con la API de U-Cursos. Además no se respeta la modularidad del proyecto. Cada componente debe estar contenido en una directiva.

2016-11-21 02:57 UTC, m4droid commented on app/scripts/directives/schedule.js
> +            if (a.fechaIni === b.fechaIni) {
Por qué cambiaste esto? La API de U-Cursos sigue retornando la llave con snake case.

2016-11-21 02:57 UTC, m4droid commented on app/scripts/directives/schedule.js
> +              return (a.fechaIni < b.fechaIni) ? -1 : 1;
Por qué cambiaste esto? La API de U-Cursos sigue retornando la llave con snake case.

2016-11-21 02:57 UTC, m4droid commented on app/scripts/directives/schedule.js
> +              return compareDates(filters.start, filters.end)(moment(event.fechaIni));
Por qué cambiaste esto? La API de U-Cursos sigue retornando la llave con snake case.

2016-11-21 04:08 UTC, crandrade commented on app/scripts/directives/schedule.js
> +              return compareDates(filters.start, filters.end)(moment(event.fechaIni));
Porque grunt me lloriquea camel case xD

2018-05-08 17:42 UTC, closed without merging